language: ruby

# only run CI-builds on gh-pages branch
branches:
  only:
    - gh-pages

rvm:
  - 2.6.3

# set execution permission on our build script
before_script:
  - npm i -g npm@6.13.7
  - npm install --global gulp-cli
  - chmod +x ./scripts/cibuild.sh

# path to our build script.
# Travis will run `bundle install` by default before running our script
script: ./scripts/cibuild.sh
exclude: [vendor]

cache: bundler # caching bundler gem packages will speed up build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev